# Mensagens em português e inglês
mensagens = {
    'pt': {
        'bemvindo': '\nBem-vindo ao Cardápio Digital Interativo!',
        'mensagem_boas_vindas': '\nEstamos muito felizes por tê-lo conosco. Aqui, cada prato é preparado com carinho e dedicação para proporcionar a você uma experiência culinária memorável.',
        'pergunta_fazer_login': '\nDeseja fazer login (suas preferências serão salvas para futuras sugestões) ou ir direto ao cardápio ?',
        'login': "\n1 - Login",
        'ir_cardapio': "2 - Ir direto ao cardápio",
        'informe_email': "\nInforme seu e-mail : ",
        'informe_senha': "\nInforme sua senha : ",
        'login_sucesso': "\nLogin efetuado com sucesso, você será direcionado ao cardápio principal.",
        'login_falhou': "\nLogin invalido, tente novamente.",
        'CARDAPIO_GERAL': "\nCARDAPIO GERAL\n",
        'CARDAPIO_DIABETICO': "\nCARDAPIO DIABETICO\n",
        'CARDAPIO_VEGETARIANO': "\nCARDAPIO VEGETARIANO\n",
        'CARDAPIO_SEM_LACTOSE': "\nCARDAPIO SEM LACTOSE\n",
        'CARDAPIO_SEM_GLUTEN': "\nCARDAPIO SEM GLUTEN\n",
        'CARDAPIO_SAZONAL': "\nCARDAPIO SAZONAL\n",
        'CARDAPIO_FAVORITO': "\nCARDAPIO FAVORITO\n",
        '1 - Geral': "1 - Geral",
        '2 - Diabetico': "2 - Diabetico",
        '3 - Vegetariano': "3 - Vegetariano",
        '4 - Sem Lactose': "4 - Sem Lactose",
        '5 - Sem Gluten': "5 - Sem Gluten",
        '6 - Sazonal': "6 - Sazonal",
        '7 - Favoritos': "7 - Favoritos",
        'escolhe_cardapio': "\nQual Cardapio deseja acessar ?\n ",
        'pedir_este_prato': "\n1 - PEDIR ESTE PRATO.",
        'nutricional': "2 - Informação Nutricional, Valor calórico e alergênicos",
        'personalize': "3 - Personalize seu prato",
        'digite_ingrediente_retirar': "Digite o ingrediente a ser RETIRADO: ",
        'digite_ingrediente_adicionar': "Digite o ingrediente a ser ADICIONADO: ",
        'sem_ingredientes_retirados': "Nenhum ingrediente será retirado.",
        'sem_ingredientes_adicionados': "Nenhum ingrediente será adicionado.",
        'lista_ingredientes_retirados': "Ingredientes a serem RETIRADOS: ",
        'lista_ingredientes_adicionados': "Ingredientes a serem ADICIONADOS: ",
        'aviso_substituir_ingredientes': "\nOs ingredientes que você já informou serão substituídos por estes.",
        'video': "4 - Vídeo de apresentação do prato",
        'video_nao_encontrado': "Arquivo de vídeo não encontrado.",
        '3 - voltar': "3 - Voltar",
        '4 - voltar': "4 - Voltar",
        '5 - voltar': "5 - Voltar",
        '6 - voltar': "6 - Voltar",
        '7 - voltar': "7 - Voltar",
        '8 - voltar': "8 - Voltar",
        'finalizar_pedido': "6 - finalizar pedido",
        'escolha': "\nEscolha uma opção: ",
        'retirar_ingrediente': "\n1 - Retirar ingrediente",
        'adicionar_ingrediente': "2 - Adicionar ingrediente",
        'aperte_enter': "\nAperte Enter para voltar a tela inicial ",
        'saida': "Saindo do programa.",
        'invalido': "Opção inválida, tente novamente.",
        'rotina_desenvolvimento': 'Rotina em desenvolvimento...',
        'aguarde': "Aguarde..."
    },
    'en': {
        'bemvindo': '\nWelcome to the Interactive Digital Menu!',
        'mensagem_boas_vindas': '\nWe are very happy to have you with us. Here, each dish is prepared with care and dedication to provide you with a memorable culinary experience.',
        'pergunta_fazer_login': '\nWould you like to log in (your preferences will be saved for future suggestions) or go directly to the menu?',
        'login': "\n1 - Login",
        'ir_cardapio': "2 - Go directly to the menu",
        'informe_email': "\nPlease enter your email: ",
        'informe_senha': "\nPlease enter your password: ",
        'login_sucesso': "\nLogin successful, you will be redirected to the main menu.",
        'login_falhou': "\nInvalid login, please try again.",
        'CARDAPIO_GERAL': "\nGENERAL MENU\n",
        'CARDAPIO_DIABETICO': "\nDIABETIC MENU\n",
        'CARDAPIO_VEGETARIANO': "\nVEGETARIAN MENU\n",
        'CARDAPIO_SEM_LACTOSE': "\nLACTOSE-FREE MENU\n",
        'CARDAPIO_SEM_GLUTEN': "\nGLUTEN-FREE MENU\n",
        'CARDAPIO_SAZONAL': "\nSEASONAL MENU\n",
        'CARDAPIO_FAVORITO': "\nFAVORITE MENU\n",
        '1 - Geral': "1 - General",
        '2 - Diabetico': "2 - Diabetic",
        '3 - Vegetariano': "3 - Vegetarian",
        '4 - Sem Lactose': "4 - Lactose-Free",
        '5 - Sem Gluten': "5 - Gluten-Free",
        '6 - Sazonal': "6 - Seasonal",
        '7 - Favoritos': "7 - Favorites",
        'escolhe_cardapio': "\nWhich menu would you like to access?\n ",
        'pedir_este_prato': "\n1 - ORDER THIS DISH.",
        'nutricional': "2 - Nutritional Information, Caloric Value and Allergens",
        'personalize': "3 - Customize your dish",
        'digite_ingrediente_retirar': "Enter the ingredient to be REMOVED: ",
        'digite_ingrediente_adicionar': "Enter the ingredient to be ADDED: ",
        'sem_ingredientes_retirados': "No ingredients will be removed.",
        'sem_ingredientes_adicionados': "No ingredients will be added.",
        'lista_ingredientes_retirados': "Ingredients to be REMOVED: ",
        'lista_ingredientes_adicionados': "Ingredients to be ADDED: ",
        'aviso_substituir_ingredientes': "\nThe ingredients you have already informed will be replaced by these.",
        'video': "4 - Video presentation of the dish",
        'video_nao_encontrado': "Video file not found.",
        '3 - voltar': "3 - Go Back",
        '4 - voltar': "4 - Go Back",
        '5 - voltar': "5 - Go Back",
        '6 - voltar': "6 - Go Back",
        '7 - voltar': "7 - Go Back",
        '8 - voltar': "8 - Go Back",
        'finalizar_pedido': "6 - finalize order",
        'escolha': "\nChoose an option: ",
        'retirar_ingrediente': "\n1 - Remove ingredient",
        'adicionar_ingrediente': "2 - Add ingredient",
        'aperte_enter': "\nPress Enter to return to the home screen ",
        'saida': "Exiting the program.",
        'invalido': "Invalid option, please try again.",
        'rotina_desenvolvimento': 'Routine under development...',
        'aguarde': "Please wait..."
    }
}
def get_mensagem_navegacao(idioma, chave):
    """Returns the message for the specified language and key."""
    return mensagens[idioma].get(chave, "Message not found")
