# Mensagens em português e inglês
mensagens = {
'pt': {
    'aguarde': "Aguarde...",
    'adicionar_ingrediente': 'Adicionar Ingrediente',
    'alergia_cliente': "Alergia: ",
    'alteracao_cadastro_cliente': 'Alterar Cadastro',
    'alterar_cadastro_cliente': 'Alterar Cadastro',
    'aperte_enter_voltar': "Aperte 'enter' para voltar.",
    'aviso_substituir_ingredientes': "Os ingredientes que você já informou serão substituídos por estes.",
    'bemvindo': 'Bem-vindo ao Cardápio Digital Interativo!',
    'cadastro_atualizado': 'Cadastro atualizado com sucesso!',
    'cadastro_de_cliente': "Cadastro de cliente",
    'cadastro_nao_encontrado': "Cadastro não Encontrado",
    'CARDAPIO_GERAL': "CARDAPIO GERAL",
    'CARDAPIO_DIABETICO': "CARDAPIO DIABETICO",
    'CARDAPIO_VEGETARIANO': "CARDAPIO VEGETARIANO",
    'CARDAPIO_SEM_LACTOSE': "CARDAPIO SEM LACTOSE",
    'CARDAPIO_SEM_GLUTEN': "CARDAPIO SEM GLUTEN",
    'CARDAPIO_SAZONAL': "CARDAPIO SAZONAL",
    'CARDAPIO_FAVORITO': "CARDAPIO FAVORITO",
    'cliente_encontrado': "Cliente Encontrado:",
    'cliente_excluido': "Cadastro excluído com sucesso!",
    'cliente_nao_encontrado': "Cliente não encontrado",
    'confirmacao_exclusao': "Deseja realmente excluir este cadastro (S/N)? ",
    'consulta_cadastro_cliente': "Consulta de Cadastro de Cliente",
    'consultar_cadastro_cliente': "Consultar cadastro",
    'diabetico': 'Diabetico',
    'digite_ingrediente_adicionar': "Digite o ingrediente a ser ADICIONADO: ",
    'digite_ingrediente_retirar': "Digite o ingrediente a ser RETIRADO: ",
    'digite_seu_telefone': "Digite seu telefone: ",
    'Digite_seu_nome': "Digite seu nome: ",
    'DIGITE_NUMERO_VALIDO': "Por favor, digite um número válido.",
    'email_cliente': 'Email: ',
    'email_invalido': "Email inválido.",
    'escolha_alteracao': 'Qual informação deseja alterar (pressione Enter para voltar): ',
    'escolha_uma_opcao': "Escolha uma opção: ",
    'escolhe_cardapio': "Qual Cardapio deseja acessar ? ",
    'excluir_cadastro_cliente': "Excluir cadastro",
    'exclusao_cadastro_cliente': "Exclusão de Cadastro de Cliente",
    'exclusao_cliente_cancelada': "Erro ao excluir cadastro",
    'Favoritos': "Favoritos",
    'favoritos': "Favoritos",
    'fazer_cadastro_cliente': "Fazer cadastro",
    'finalizar_pedido': "Finalizar pedido",
    'geral': "Geral",
    'id_cliente': 'ID: ',
    'inclusão_cadastro_cliente': "Inclusão de cadastro de cliente.",
    'informe_seu_email': "Informe seu email (enter para voltar): ",
    'informe_senha': "Informe sua senha: ",
    'informe_senha_novamente': "Informe sua senha novamente: ",
    'intolerante_lactose': "Intolerante a Lactose",
    'intolerante_gluten': "Intolerante a glúten",
    'invalido': "Opção inválida, tente novamente.",
    'ir_cardapio': "Ir direto ao cardápio",
    'lista_ingredientes_adicionados': "Ingredientes a serem ADICIONADOS: ",
    'lista_ingredientes_retirados': "Ingredientes a serem RETIRADOS: ",
    'login': "Login",
    'login_falhou': "Login invalido, tente novamente.",
    'login_sucesso': "Login efetuado com sucesso, você será direcionado ao cardápio principal.",
    'manutencao_cadastro_cliente': "Manutenção de Cadastro de Cliente",
    'mensagem_boas_vindas': 'Estamos muito felizes por tê-lo conosco. Aqui, cada prato é preparado com carinho e dedicação para proporcionar a você uma experiência culinária memorável.',
    'nenhum_cliente_cadastrado': "Nenhum Cliente Cadastrado",
    'nenhuma': 'Nenhuma',
    'nome_cliente': 'Nome: ',
    'nova_alergia': 'Nova alergia (pressione Enter para manter a atual): ',
    'nova_restricao_alimentar': '''Nova restrição alimentar (pressione Enter para manter a atual):
  1 - Diabético
  2 - Vegetariano
  3 - Intolerante a Lactose
  4 - Intolerante a Glúten
  5 - Nenhuma
  ''',
    'novo_nome': 'Novo nome (pressione Enter para manter o atual): ',
    'novo_telefone': 'Novo telefone (pressione Enter para manter o atual): ',
    'nutricional': "Informação Nutricional, Valor calórico e alergênicos",
    'opcao_invalida': 'Opção inválida, tente novamente.',
    'pedir_este_prato': "PEDIR ESTE PRATO.",
    'pergunta_fazer_login': 'Deseja fazer login (suas preferências serão salvas para futuras sugestões) ou ir direto ao cardápio ?',
    'personalize': "Personalize seu prato",
    'restricao_alimentar_cliente': 'Restrição Alimentar: ',
    'retirar_ingrediente': "Retirar ingrediente",
    'rotina_desenvolvimento': 'Rotina em desenvolvimento...',
    'saida': "Saindo do programa.",
    'sazonal': "Sazonal",
    'sem_Gluten': "Sem Gluten",
    'sem_Lactose': "Sem Lactose",
    'sem_ingredientes_adicionados': "Nenhum ingrediente será adicionado.",
    'sem_ingredientes_retirados': "Nenhum ingrediente será retirado.",
    'senhas_nao_conferem': "Senhas não conferem. Tente novamente.",
    'telefone_cliente': 'Telefone: ',
    'vegetariano': 'Vegetariano',
    'video': "Vídeo de apresentação do prato",
    'video_nao_encontrado': "Arquivo de vídeo não encontrado.",
    'voltar': "Voltar"
},
    'en': {

    },
    'es': {
    }
}
def get_mensagem_navegacao(idioma, chave):
    """Returns the message for the specified language and key."""
    return mensagens[idioma].get(chave, "Message not found")
