# Mensagens em português e inglês
mensagens = {
    'pt': {
        'Prato': "\nSTROGONOFF VEGETARIANO",
        'descrição': "Pedaços suculentos de cogumelos frescos e proteína de soja texturizada, delicadamente cozidos em um molho cremoso e rico, repleto de temperos aromáticos. Servido com arroz soltinho e batatas douradas, este prato é uma celebração da culinária vegetariana, perfeito para saciar seus desejos sem abrir mão do sabor e da tradição.",
        'lista_ingredientes': "\nIngredientes: Frango, sal, pimenta, azeite, cebola, beringela, tomate, salsa, creme de leite, ketchup, mostarda",
        'preco_tempo': "\nPreço: R$ 45,00 - Tempo estimado de preparo: 20 minutos",
        'pedir_este_prato': "\n1 - PEDIR ESTE PRATO.",
        'nutricional': "2 - Informação Nutricional, Valor calórico e alergênicos",
        'personalize': "3 - Personalize seu prato",
        'ingredientes_retirados': "Digite o ingrediente a ser RETIRADO: ",
        'sem_ingredientes_retirados': "Nenhum ingrediente será retirado.",
        'sem_ingredientes_adicionados': "Nenhum ingrediente será adicionado.",
        'ingredientes_adicionados': "Digite o ingrediente a ser ADICIONADO: ",
        'lista_ingredientes_retirados': "Ingredientes a serem RETIRADOS: ",
        'lista_ingredientes_adicionados': "Ingredientes a serem ADICIONADOS: ",
        'aviso_substituir_ingredientes': "\nOs ingredientes que você já informou serão substituídos por estes.",
        'video': "4 - Vídeo de apresentação do prato",
        'video_nao_encontrado': "Arquivo de vídeo não encontrado.",
        '3 voltar': "3 - Voltar",
        '4 voltar': "4 - Voltar",
        '5 voltar': "5 - Voltar",
        'finalizar_pedido': "6 - finalizar pedido",
        'escolha': "\nEscolha uma opção: ",
        'info_nutricional': "\nInformação Nutricional (Porção de 60g):",
        'calorias': "\nValor Calórico: 114,6kcal (5,3% VD)",
        'carboidratos': "Carboidratos: 2,77g (1% VD)",
        'proteinas': "Proteínas: 7,6g (9,3% VD)",
        'gorduras': "Gorduras totais: 7,8g (15,6% VD)",
        'saturadas': "Gorduras saturadas: 0g",
        'trans': "Gorduras trans: 0g",
        'fibra': "Fibra alimentar: 2,9g (8,8% VD)",
        'sodio': "Sódio: 114mg (6% VD)",
        'base_dieta': "*Valores diários com base em dieta de 2.000kcal ou 8.400kj.",
        'atencao_lactose': "Atenção : Este alimento CONTÉM LACTOSE",
        'retirar_ingrediente': "\n1 - Retirar ingrediente",
        'adicionar_ingrediente': "2 - Adicionar ingrediente",
        'aperte_enter': "\nAperte Enter para voltar a tela inicial ",
        'saida': "Saindo do programa.",
        'invalido': "Opção inválida, tente novamente.",
        'aguarde': "Aguarde..."
    },
    'en': {
        'dish': "\nVegetarian Stroganoff",
        'ingredientes': "1 - Learn the ingredients",
        'nutricional': "2 - Nutritional Information, Caloric Value and Allergens",
        'preco': "3 - Price and Estimated Preparation Time",
        'video': "4 - Presentation Video of the Dish",
        'sair': "5 - Exit",
        'video_nao_encontrado': "Video file not found.",
        'escolha': "\nChoose an option: ",
        'description': "\nSucculent chunks of fresh mushrooms and textured soy protein, delicately cooked in a rich, creamy sauce bursting with aromatic seasonings. Served with fluffy rice and golden potatoes, this dish is a celebration of vegetarian cuisine, perfect for satisfying your cravings without giving up flavor and tradition.",
        'lista_ingredientes': "\nIngredients:\nChicken, salt, pepper, olive oil, onion, eggplant, tomato, parsley, cream, ketchup, mustard",
        'aperte_enter': "\nPress Enter to return to the main screen ",
        'info_nutricional': "\nNutritional Information (Serving of 60g):",
        'calorias': "\nCaloric Value: 114.6kcal (5.3% DV)",
        'carboidratos': "Carbohydrates: 2.77g (1% DV)",
        'proteinas': "Proteins: 7.6g (9.3% DV)",
        'gorduras': "Total Fats: 7.8g (15.6% DV)",
        'saturadas': "Saturated Fats: 0g",
        'trans': "Trans Fats: 0g",
        'fibra': "Dietary Fiber: 2.9g (8.8% DV)",
        'sodio': "Sodium: 114mg (6% DV)",
        'base_dieta': "*Daily values based on a 2,000 calorie or 8,400kj diet.",
        'atencao_lactose': "\nAttention: This food CONTAINS LACTOSE",
        'saida': "Exiting the program.",
        'invalido': "Invalid option, try again.",
        'aguarde': "Please wait...",
        'preco_tempo': "\nPrice: $45.00 - Estimated Preparation Time: 20 minutes"
    }
}

def get_mensagem(idioma, chave):
    """Retorna a mensagem para o idioma e chave especificados."""
    return mensagens[idioma].get(chave, "Mensagem não encontrada")
