# Mensagens em português, inglês, espanhol, italiano e alemão
mensagens = {
'pt': {
    'aguarde': "Aguarde...",
    'adicionar_ingrediente': 'Adicionar Ingrediente',
    'alergia_cliente': "Alergia: ",
    'alteracao_cadastro_cliente': 'Alterar Cadastro',
    'alterar_cadastro_cliente': 'Alterar Cadastro',
    'aperte_enter_voltar': "Aperte 'enter' para voltar.",
    'aviso_substituir_ingredientes': "Os ingredientes que você já informou serão substituídos por estes.",
    'bemvindo': 'Bem-vindo ao Cardápio Digital Interativo!',
    'cadastro_atualizado': 'Cadastro atualizado com sucesso!',
    'cadastro_de_cliente': "Cadastro de cliente",
    'cadastro_nao_encontrado': "Cadastro não Encontrado",
    'CARDAPIO_GERAL': "CARDAPIO GERAL",
    'CARDAPIO_DIABETICO': "CARDAPIO DIABETICO",
    'CARDAPIO_VEGETARIANO': "CARDAPIO VEGETARIANO",
    'CARDAPIO_SEM_LACTOSE': "CARDAPIO SEM LACTOSE",
    'CARDAPIO_SEM_GLUTEN': "CARDAPIO SEM GLUTEN",
    'CARDAPIO_SAZONAL': "CARDAPIO SAZONAL",
    'CARDAPIO_FAVORITO': "CARDAPIO FAVORITO",
    'cliente_encontrado': "Cliente Encontrado:",
    'cliente_excluido': "Cadastro excluído com sucesso!",
    'cliente_nao_encontrado': "Cliente não encontrado",
    'confirmacao_exclusao': "Deseja realmente excluir este cadastro (S/N)? ",
    'consulta_cadastro_cliente': "Consulta de Cadastro de Cliente",
    'consultar_cadastro_cliente': "Consultar cadastro",
    'diabetico': 'Diabetico',
    'digite_ingrediente_adicionar': "Digite o ingrediente a ser ADICIONADO: ",
    'digite_ingrediente_retirar': "Digite o ingrediente a ser RETIRADO: ",
    'digite_seu_telefone': "Digite seu telefone: ",
    'Digite_seu_nome': "Digite seu nome: ",
    'DIGITE_NUMERO_VALIDO': "Por favor, digite um número válido.",
    'email_cliente': 'Email: ',
    'email_invalido': "Email inválido.",
    'email_nao_encontrado': "Email não encontrado.",
    'escolha_alteracao': 'Qual informação deseja alterar (pressione Enter para voltar): ',
    'escolha_uma_opcao': "Escolha uma opção: ",
    'escolhe_cardapio': "Qual Cardapio deseja acessar ? ",
    'excluir_cadastro_cliente': "Excluir cadastro",
    'exclusao_cadastro_cliente': "Exclusão de Cadastro de Cliente",
    'exclusao_cliente_cancelada': "Erro ao excluir cadastro",
    'favoritos': "Favoritos",
    'fazer_cadastro_cliente': "Fazer cadastro",
    'finalizar_pedido': "Finalizar pedido",
    'geral': "Geral",
    'id_cliente': 'ID: ',
    'inclusão_cadastro_cliente': "Inclusão de cadastro de cliente.",
    'informe_seu_email': "Informe seu email (enter para voltar): ",
    'informe_seu_email_cadastrado': "Informe seu email cadastrado : ",
    'informe_senha': "Informe sua senha: ",
    'informe_senha_novamente': "Informe sua senha novamente: ",
    'intolerante_lactose': "Intolerante a Lactose",
    'intolerante_gluten': "Intolerante a glúten",
    'invalido': "Opção inválida, tente novamente.",
    'ir_cardapio': "Ir direto ao cardápio",
    'lista_ingredientes_adicionados': "Ingredientes a serem ADICIONADOS: ",
    'lista_ingredientes_retirados': "Ingredientes a serem RETIRADOS: ",
    'login': "Login",
    'login_falhou': "Login invalido, tente novamente.",
    'login_sucesso': "Login efetuado com sucesso, você será direcionado ao cardápio principal.",
    'manutencao_cadastro_cliente': "Manutenção de Cadastro de Cliente",
    'mensagem_boas_vindas': 'Estamos muito felizes por tê-lo conosco. Aqui, cada prato é preparado com carinho e dedicação para proporcionar a você uma experiência culinária memorável.',
    'nenhum_cliente_cadastrado': "Nenhum Cliente Cadastrado",
    'nenhuma': 'Nenhuma',
    'nome_cliente': 'Nome: ',
    'nova_alergia': 'Nova alergia (pressione Enter para manter a atual): ',
    'nova_restricao_alimentar': '''Nova restrição alimentar (pressione Enter para manter a atual):
  1 - Diabético
  2 - Vegetariano
  3 - Intolerante a Lactose
  4 - Intolerante a Glúten
  5 - Nenhuma
  ''',
    'novo_nome': 'Novo nome (pressione Enter para manter o atual): ',
    'novo_telefone': 'Novo telefone (pressione Enter para manter o atual): ',
    'nutricional': "Informação Nutricional, Valor calórico e alergênicos",
    'opcao_invalida': 'Opção inválida, tente novamente.',
    'pedir_este_prato': "PEDIR ESTE PRATO.",
    'pergunta_fazer_login': 'Deseja fazer login (suas preferências serão salvas para futuras sugestões) ou ir direto ao cardápio ?',
    'personalize': "Personalize seu prato",
    'restricao_alimentar_cliente': 'Restrição Alimentar: ',
    'retirar_ingrediente': "Retirar ingrediente",
    'rotina_desenvolvimento': 'Rotina em desenvolvimento...',
    'saida': "Saindo do programa.",
    'sazonal': "Sazonal",
    'sem_Gluten': "Sem Gluten",
    'sem_Lactose': "Sem Lactose",
    'sem_ingredientes_adicionados': "Nenhum ingrediente será adicionado.",
    'sem_ingredientes_retirados': "Nenhum ingrediente será retirado.",
    'senhas_nao_conferem': "Senhas não conferem. Tente novamente.",
    'telefone_cliente': 'Telefone: ',
    'vegetariano': 'Vegetariano',
    'video': "Vídeo de apresentação do prato",
    'video_nao_encontrado': "Arquivo de vídeo não encontrado.",
    'voltar': "Voltar"
},
'en': {
    'aguarde': "Please wait...",
    'adicionar_ingrediente': 'Add Ingredient',
    'alergia_cliente': "Allergy: ",
    'alteracao_cadastro_cliente': 'Update Registration',
    'alterar_cadastro_cliente': 'Update Registration',
    'aperte_enter_voltar': "Press 'enter' to go back.",
    'aviso_substituir_ingredientes': "The ingredients you have already informed will be replaced by these.",
    'bemvindo': 'Welcome to the Interactive Digital Menu!',
    'cadastro_atualizado': 'Registration successfully updated!',
    'cadastro_de_cliente': "Customer Registration",
    'cadastro_nao_encontrado': "Registration Not Found",
    'CARDAPIO_GERAL': "GENERAL MENU",
    'CARDAPIO_DIABETICO': "DIABETIC MENU",
    'CARDAPIO_VEGETARIANO': "VEGETARIAN MENU",
    'CARDAPIO_SEM_LACTOSE': "LACTOSE-FREE MENU",
    'CARDAPIO_SEM_GLUTEN': "GLUTEN-FREE MENU",
    'CARDAPIO_SAZONAL': "SEASONAL MENU",
    'CARDAPIO_FAVORITO': "FAVORITE MENU",
    'cliente_encontrado': "Customer Found:",
    'cliente_excluido': "Registration successfully deleted!",
    'cliente_nao_encontrado': "Customer not found",
    'confirmacao_exclusao': "Do you really want to delete this registration (Y/N)? ",
    'consulta_cadastro_cliente': "Customer Registration Query",
    'consultar_cadastro_cliente': "Consult registration",
    'diabetico': 'Diabetic',
    'digite_ingrediente_adicionar': "Enter the ingredient to be ADDED: ",
    'digite_ingrediente_retirar': "Enter the ingredient to be REMOVED: ",
    'digite_seu_telefone': "Enter your phone number: ",
    'Digite_seu_nome': "Enter your name: ",
    'DIGITE_NUMERO_VALIDO': "Please enter a valid number.",
    'email_cliente': 'Email: ',
    'email_invalido': "Invalid email.",
    'email_nao_encontrado': "Email not found.",
    'escolha_alteracao': 'Which information do you want to update (press Enter to go back): ',
    'escolha_uma_opcao': "Choose an option: ",
    'escolhe_cardapio': "Which menu would you like to access? ",
    'excluir_cadastro_cliente': "Delete registration",
    'exclusao_cadastro_cliente': "Customer Registration Deletion",
    'exclusao_cliente_cancelada': "Error deleting registration",
    'favoritos': "Favorites",
    'fazer_cadastro_cliente': "Register",
    'finalizar_pedido': "Finalize order",
    'geral': "General",
    'id_cliente': 'ID: ',
    'inclusão_cadastro_cliente': "Customer registration inclusion.",
    'informe_seu_email': "Enter your email (press enter to go back): ",
    'informe_seu_email_cadastrado': "Enter your registered email: ",
    'informe_senha': "Enter your password: ",
    'informe_senha_novamente': "Re-enter your password: ",
    'intolerante_lactose': "Lactose Intolerant",
    'intolerante_gluten': "Gluten Intolerant",
    'invalido': "Invalid option, please try again.",
    'ir_cardapio': "Go directly to the menu",
    'lista_ingredientes_adicionados': "Ingredients to be ADDED: ",
    'lista_ingredientes_retirados': "Ingredients to be REMOVED: ",
    'login': "Login",
    'login_falhou': "Invalid login, please try again.",
    'login_sucesso': "Login successful, you will be redirected to the main menu.",
    'manutencao_cadastro_cliente': "Customer Registration Maintenance",
    'mensagem_boas_vindas': 'We are very happy to have you with us. Here, each dish is prepared with care and dedication to provide you with a memorable culinary experience.',
    'nenhum_cliente_cadastrado': "No Customer Registered",
    'nenhuma': 'None',
    'nome_cliente': 'Name: ',
    'nova_alergia': 'New allergy (press Enter to keep current): ',
    'nova_restricao_alimentar': '''New dietary restriction (press Enter to keep current):
  1 - Diabetic
  2 - Vegetarian
  3 - Lactose Intolerant
  4 - Gluten Intolerant
  5 - None
  ''',
    'novo_nome': 'New name (press Enter to keep current): ',
    'novo_telefone': 'New phone number (press Enter to keep current): ',
    'nutricional': "Nutritional Information, Caloric Value, and Allergens",
    'opcao_invalida': 'Invalid option, please try again.',
    'pedir_este_prato': "ORDER THIS DISH.",
    'pergunta_fazer_login': 'Do you want to log in (your preferences will be saved for future suggestions) or go directly to the menu?',
    'personalize': "Customize your dish",
    'restricao_alimentar_cliente': 'Dietary Restriction: ',
    'retirar_ingrediente': "Remove ingredient",
    'rotina_desenvolvimento': 'Routine in development...',
    'saida': "Exiting the program.",
    'sazonal': "Seasonal",
    'sem_Gluten': "Gluten-Free",
    'sem_Lactose': "Lactose-Free",
    'sem_ingredientes_adicionados': "No ingredients will be added.",
    'sem_ingredientes_retirados': "No ingredients will be removed.",
    'senhas_nao_conferem': "Passwords do not match. Please try again.",
    'telefone_cliente': 'Phone: ',
    'vegetariano': 'Vegetarian',
    'video': "Presentation video of the dish",
    'video_nao_encontrado': "Video file not found.",
    'voltar': "Back"
},
'es': {
    'aguarde': "Espere...",
    'adicionar_ingrediente': 'Añadir Ingrediente',
    'alergia_cliente': "Alergia: ",
    'alteracao_cadastro_cliente': 'Actualizar Registro',
    'alterar_cadastro_cliente': 'Actualizar Registro',
    'aperte_enter_voltar': "Presione 'enter' para volver.",
    'aviso_substituir_ingredientes': "Los ingredientes que ya ha informado serán reemplazados por estos.",
    'bemvindo': '¡Bienvenido al Menú Digital Interactivo!',
    'cadastro_atualizado': '¡Registro actualizado con éxito!',
    'cadastro_de_cliente': "Registro de cliente",
    'cadastro_nao_encontrado': "Registro No Encontrado",
    'CARDAPIO_GERAL': "MENÚ GENERAL",
    'CARDAPIO_DIABETICO': "MENÚ DIABÉTICO",
    'CARDAPIO_VEGETARIANO': "MENÚ VEGETARIANO",
    'CARDAPIO_SEM_LACTOSE': "MENÚ SIN LACTOSA",
    'CARDAPIO_SEM_GLUTEN': "MENÚ SIN GLUTEN",
    'CARDAPIO_SAZONAL': "MENÚ ESTACIONAL",
    'CARDAPIO_FAVORITO': "MENÚ FAVORITO",
    'cliente_encontrado': "Cliente Encontrado:",
    'cliente_excluido': "¡Registro eliminado con éxito!",
    'cliente_nao_encontrado': "Cliente no encontrado",
    'confirmacao_exclusao': "¿Realmente desea eliminar este registro (S/N)? ",
    'consulta_cadastro_cliente': "Consulta de Registro de Cliente",
    'consultar_cadastro_cliente': "Consultar registro",
    'diabetico': 'Diabético',
    'digite_ingrediente_adicionar': "Ingrese el ingrediente a AÑADIR: ",
    'digite_ingrediente_retirar': "Ingrese el ingrediente a ELIMINAR: ",
    'digite_seu_telefone': "Ingrese su número de teléfono: ",
    'Digite_seu_nome': "Ingrese su nombre: ",
    'DIGITE_NUMERO_VALIDO': "Por favor, ingrese un número válido.",
    'email_cliente': 'Correo electrónico: ',
    'email_invalido': "Correo electrónico inválido.",
    'email_nao_encontrado': "Correo electrónico no encontrado.",
    'escolha_alteracao': '¿Qué información desea actualizar (presione Enter para volver): ',
    'escolha_uma_opcao': "Elija una opción: ",
    'escolhe_cardapio': "¿A qué menú le gustaría acceder? ",
    'excluir_cadastro_cliente': "Eliminar registro",
    'exclusao_cadastro_cliente': "Eliminación de Registro de Cliente",
    'exclusao_cliente_cancelada': "Error al eliminar el registro",
    'favoritos': "Favoritos",
    'fazer_cadastro_cliente': "Registrar",
    'finalizar_pedido': "Finalizar pedido",
    'geral': "General",
    'id_cliente': 'ID: ',
    'inclusão_cadastro_cliente': "Inclusión de registro de cliente.",
    'informe_seu_email': "Ingrese su correo electrónico (presione enter para volver): ",
    'informe_seu_email_cadastrado': "Ingrese su correo electrónico registrado: ",
    'informe_senha': "Ingrese su contraseña: ",
    'informe_senha_novamente': "Reingrese su contraseña: ",
    'intolerante_lactose': "Intolerante a la Lactosa",
    'intolerante_gluten': "Intolerante al Gluten",
    'invalido': "Opción inválida, por favor intente nuevamente.",
    'ir_cardapio': "Ir directamente al menú",
    'lista_ingredientes_adicionados': "Ingredientes a AÑADIR: ",
    'lista_ingredientes_retirados': "Ingredientes a ELIMINAR: ",
    'login': "Iniciar sesión",
    'login_falhou': "Inicio de sesión inválido, por favor intente nuevamente.",
    'login_sucesso': "Inicio de sesión exitoso, será redirigido al menú principal.",
    'manutencao_cadastro_cliente': "Mantenimiento de Registro de Cliente",
    'mensagem_boas_vindas': 'Estamos muy felices de tenerlo con nosotros. Aquí, cada plato se prepara con cuidado y dedicación para brindarle una experiencia culinaria memorable.',
    'nenhum_cliente_cadastrado': "Ningún Cliente Registrado",
    'nenhuma': 'Ninguna',
    'nome_cliente': 'Nombre: ',
    'nova_alergia': 'Nueva alergia (presione Enter para mantener la actual): ',
    'nova_restricao_alimentar': '''Nueva restricción alimentaria (presione Enter para mantener la actual):
  1 - Diabético
  2 - Vegetariano
  3 - Intolerante a la Lactosa
  4 - Intolerante al Gluten
  5 - Ninguna
  ''',
    'novo_nome': 'Nuevo nombre (presione Enter para mantener el actual): ',
    'novo_telefone': 'Nuevo número de teléfono (presione Enter para mantener el actual): ',
    'nutricional': "Información Nutricional, Valor Calórico y Alérgenos",
    'opcao_invalida': 'Opción inválida, por favor intente nuevamente.',
    'pedir_este_prato': "PEDIR ESTE PLATO.",
    'pergunta_fazer_login': '¿Desea iniciar sesión (sus preferencias se guardarán para futuras sugerencias) o ir directamente al menú?',
    'personalize': "Personalice su plato",
    'restricao_alimentar_cliente': 'Restricción Alimentaria: ',
    'retirar_ingrediente': "Eliminar ingrediente",
    'rotina_desenvolvimento': 'Rutina en desarrollo...',
    'saida': "Saliendo del programa.",
    'sazonal': "Estacional",
    'sem_Gluten': "Sin Gluten",
    'sem_Lactose': "Sin Lactosa",
    'sem_ingredientes_adicionados': "No se añadirán ingredientes.",
    'sem_ingredientes_retirados': "No se eliminarán ingredientes.",
    'senhas_nao_conferem': "Las contraseñas no coinciden. Por favor, intente nuevamente.",
    'telefone_cliente': 'Teléfono: ',
    'vegetariano': 'Vegetariano',
    'video': "Video de presentación del plato",
    'video_nao_encontrado': "Archivo de video no encontrado.",
    'voltar': "Volver"
},
'it': {
    'aguarde': "Attendere prego...",
    'adicionar_ingrediente': 'Aggiungi Ingrediente',
    'alergia_cliente': "Allergia: ",
    'alteracao_cadastro_cliente': 'Aggiorna Registrazione',
    'alterar_cadastro_cliente': 'Aggiorna Registrazione',
    'aperte_enter_voltar': "Premere 'enter' per tornare indietro.",
    'aviso_substituir_ingredientes': "Gli ingredienti che hai già informato verranno sostituiti da questi.",
    'bemvindo': 'Benvenuto nel Menu Digitale Interattivo!',
    'cadastro_atualizado': 'Registrazione aggiornata con successo!',
    'cadastro_de_cliente': "Registrazione Cliente",
    'cadastro_nao_encontrado': "Registrazione Non Trovata",
    'CARDAPIO_GERAL': "MENU GENERALE",
    'CARDAPIO_DIABETICO': "MENU DIABETICO",
    'CARDAPIO_VEGETARIANO': "MENU VEGETARIANO",
    'CARDAPIO_SEM_LACTOSE': "MENU SENZA LATTOSIO",
    'CARDAPIO_SEM_GLUTEN': "MENU SENZA GLUTINE",
    'CARDAPIO_SAZONAL': "MENU STAGIONALE",
    'CARDAPIO_FAVORITO': "MENU PREFERITO",
    'cliente_encontrado': "Cliente Trovato:",
    'cliente_excluido': "Registrazione eliminata con successo!",
    'cliente_nao_encontrado': "Cliente non trovato",
    'confirmacao_exclusao': "Vuoi davvero eliminare questa registrazione (S/N)? ",
    'consulta_cadastro_cliente': "Consulta Registrazione Cliente",
    'consultar_cadastro_cliente': "Consulta registrazione",
    'diabetico': 'Diabetico',
    'digite_ingrediente_adicionar': "Inserisci l'ingrediente da AGGIUNGERE: ",
    'digite_ingrediente_retirar': "Inserisci l'ingrediente da RIMUOVERE: ",
    'digite_seu_telefone': "Inserisci il tuo numero di telefono: ",
    'Digite_seu_nome': "Inserisci il tuo nome: ",
    'DIGITE_NUMERO_VALIDO': "Per favore, inserisci un numero valido.",
    'email_cliente': 'Email: ',
    'email_invalido': "Email non valida.",
    'email_nao_encontrado': "Email non trovata.",
    'escolha_alteracao': 'Quale informazione vuoi aggiornare (premi Enter per tornare indietro): ',
    'escolha_uma_opcao': "Scegli un'opzione: ",
    'escolhe_cardapio': "Quale menu desideri accedere? ",
    'excluir_cadastro_cliente': "Elimina registrazione",
    'exclusao_cadastro_cliente': "Eliminazione Registrazione Cliente",
    'exclusao_cliente_cancelada': "Errore nell'eliminazione della registrazione",
    'favoritos': "Preferiti",
    'fazer_cadastro_cliente': "Registrati",
    'finalizar_pedido': "Finalizza ordine",
    'geral': "Generale",
    'id_cliente': 'ID: ',
    'inclusão_cadastro_cliente': "Inclusione registrazione cliente.",
    'informe_seu_email': "Inserisci la tua email (premi enter per tornare indietro): ",
    'informe_seu_email_cadastrado': "Inserisci la tua email registrata: ",
    'informe_senha': "Inserisci la tua password: ",
    'informe_senha_novamente': "Reinserisci la tua password: ",
    'intolerante_lactose': "Intollerante al Lattosio",
    'intolerante_gluten': "Intollerante al Glutine",
    'invalido': "Opzione non valida, per favore riprova.",
    'ir_cardapio': "Vai direttamente al menu",
    'lista_ingredientes_adicionados': "Ingredienti da AGGIUNGERE: ",
    'lista_ingredientes_retirados': "Ingredienti da RIMUOVERE: ",
    'login': "Accedi",
    'login_falhou': "Accesso non valido, per favore riprova.",
    'login_sucesso': "Accesso effettuato con successo, verrai reindirizzato al menu principale.",
    'manutencao_cadastro_cliente': "Manutenzione Registrazione Cliente",
    'mensagem_boas_vindas': 'Siamo molto felici di averti con noi. Qui, ogni piatto è preparato con cura e dedizione per offrirti un\'esperienza culinaria indimenticabile.',
    'nenhum_cliente_cadastrado': "Nessun Cliente Registrato",
    'nenhuma': 'Nessuna',
    'nome_cliente': 'Nome: ',
    'nova_alergia': 'Nuova allergia (premi Enter per mantenere l\'attuale): ',
    'nova_restricao_alimentar': '''Nuova restrizione alimentare (premi Enter per mantenere l\'attuale):
  1 - Diabetico
  2 - Vegetariano
  3 - Intollerante al Lattosio
  4 - Intollerante al Glutine
  5 - Nessuna
  ''',
    'novo_nome': 'Nuovo nome (premi Enter per mantenere l\'attuale): ',
    'novo_telefone': 'Nuovo numero di telefono (premi Enter per mantenere l\'attuale): ',
    'nutricional': "Informazioni Nutrizionali, Valore Calorico e Allergeni",
    'opcao_invalida': 'Opzione non valida, per favore riprova.',
    'pedir_este_prato': "ORDINA QUESTO PIATTO.",
    'pergunta_fazer_login': 'Vuoi accedere (le tue preferenze saranno salvate per suggerimenti futuri) o andare direttamente al menu?',
    'personalize': "Personalizza il tuo piatto",
    'restricao_alimentar_cliente': 'Restrizione Alimentare: ',
    'retirar_ingrediente': "Rimuovi ingrediente",
    'rotina_desenvolvimento': 'Routine in sviluppo...',
    'saida': "Uscendo dal programma.",
    'sazonal': "Stagionale",
    'sem_Gluten': "Senza Glutine",
    'sem_Lactose': "Senza Lattosio",
    'sem_ingredientes_adicionados': "Nessun ingrediente sarà aggiunto.",
    'sem_ingredientes_retirados': "Nessun ingrediente sarà rimosso.",
    'senhas_nao_conferem': "Le password non corrispondono. Per favore riprova.",
    'telefone_cliente': 'Telefono: ',
    'vegetariano': 'Vegetariano',
    'video': "Video di presentazione del piatto",
    'video_nao_encontrado': "File video non trovato.",
    'voltar': "Indietro"
},
'de': {
    'aguarde': "Bitte warten...",
    'adicionar_ingrediente': 'Zutat hinzufügen',
    'alergia_cliente': "Allergie: ",
    'alteracao_cadastro_cliente': 'Registrierung aktualisieren',
    'alterar_cadastro_cliente': 'Registrierung aktualisieren',
    'aperte_enter_voltar': "Drücken Sie 'Enter' um zurückzukehren.",
    'aviso_substituir_ingredientes': "Die Zutaten, die Sie bereits angegeben haben, werden durch diese ersetzt.",
    'bemvindo': 'Willkommen im Interaktiven Digitalen Menü!',
    'cadastro_atualizado': 'Registrierung erfolgreich aktualisiert!',
    'cadastro_de_cliente': "Kundenregistrierung",
    'cadastro_nao_encontrado': "Registrierung nicht gefunden",
    'CARDAPIO_GERAL': "ALLGEMEINES MENÜ",
    'CARDAPIO_DIABETICO': "DIABETIKERMENÜ",
    'CARDAPIO_VEGETARIANO': "VEGETARISCHES MENÜ",
    'CARDAPIO_SEM_LACTOSE': "LAKTOSEFREIES MENÜ",
    'CARDAPIO_SEM_GLUTEN': "GLUTENFREIES MENÜ",
    'CARDAPIO_SAZONAL': "SAISONALMENÜ",
    'CARDAPIO_FAVORITO': "FAVORITENMENÜ",
    'cliente_encontrado': "Kunde gefunden:",
    'cliente_excluido': "Registrierung erfolgreich gelöscht!",
    'cliente_nao_encontrado': "Kunde nicht gefunden",
    'confirmacao_exclusao': "Möchten Sie diese Registrierung wirklich löschen (J/N)? ",
    'consulta_cadastro_cliente': "Kundenregistrierung abfragen",
    'consultar_cadastro_cliente': "Registrierung abfragen",
    'diabetico': 'Diabetiker',
    'digite_ingrediente_adicionar': "Geben Sie die hinzuzufügende Zutat ein: ",
    'digite_ingrediente_retirar': "Geben Sie die zu entfernende Zutat ein: ",
    'digite_seu_telefone': "Geben Sie Ihre Telefonnummer ein: ",
    'Digite_seu_nome': "Geben Sie Ihren Namen ein: ",
    'DIGITE_NUMERO_VALIDO': "Bitte geben Sie eine gültige Nummer ein.",
    'email_cliente': 'E-Mail: ',
    'email_invalido': "Ungültige E-Mail.",
    'email_nao_encontrado': "E-Mail nicht gefunden.",
    'escolha_alteracao': 'Welche Information möchten Sie aktualisieren (drücken Sie Enter um zurückzukehren): ',
    'escolha_uma_opcao': "Wählen Sie eine Option: ",
    'escolhe_cardapio': "Welches Menü möchten Sie aufrufen? ",
    'excluir_cadastro_cliente': "Registrierung löschen",
    'exclusao_cadastro_cliente': "Kundenregistrierung löschen",
    'exclusao_cliente_cancelada': "Fehler beim Löschen der Registrierung",
    'favoritos': "Favoriten",
    'fazer_cadastro_cliente': "Registrieren",
    'finalizar_pedido': "Bestellung abschließen",
    'geral': "Allgemein",
    'id_cliente': 'ID: ',
    'inclusão_cadastro_cliente': "Kundenregistrierung hinzufügen.",
    'informe_seu_email': "Geben Sie Ihre E-Mail-Adresse ein (drücken Sie Enter um zurückzukehren): ",
    'informe_seu_email_cadastrado': "Geben Sie Ihre registrierte E-Mail-Adresse ein: ",
    'informe_senha': "Geben Sie Ihr Passwort ein: ",
    'informe_senha_novamente': "Geben Sie Ihr Passwort erneut ein: ",
    'intolerante_lactose': "Laktoseintolerant",
    'intolerante_gluten': "Glutenintolerant",
    'invalido': "Ungültige Option, bitte versuchen Sie es erneut.",
    'ir_cardapio': "Direkt zum Menü",
    'lista_ingredientes_adicionados': "Hinzugefügte Zutaten: ",
    'lista_ingredientes_retirados': "Entfernte Zutaten: ",
    'login': "Anmelden",
    'login_falhou': "Ungültige Anmeldung, bitte versuchen Sie es erneut.",
    'login_sucesso': "Anmeldung erfolgreich, Sie werden zum Hauptmenü weitergeleitet.",
    'manutencao_cadastro_cliente': "Kundenregistrierung Wartung",
    'mensagem_boas_vindas': 'Wir freuen uns sehr, Sie bei uns zu haben. Hier wird jedes Gericht mit Sorgfalt und Hingabe zubereitet, um Ihnen ein unvergessliches kulinarisches Erlebnis zu bieten.',
    'nenhum_cliente_cadastrado': "Kein Kunde registriert",
    'nenhuma': 'Keine',
    'nome_cliente': 'Name: ',
    'nova_alergia': 'Neue Allergie (drücken Sie Enter um die aktuelle zu behalten): ',
    'nova_restricao_alimentar': '''Neue diätetische Einschränkung (drücken Sie Enter um die aktuelle zu behalten):
  1 - Diabetiker
  2 - Vegetarier
  3 - Laktoseintolerant
  4 - Glutenintolerant
  5 - Keine
  ''',
    'novo_nome': 'Neuer Name (drücken Sie Enter um den aktuellen zu behalten): ',
    'novo_telefone': 'Neue Telefonnummer (drücken Sie Enter um die aktuelle zu behalten): ',
    'nutricional': "Nährwertinformationen, Kalorienwert und Allergene",
    'opcao_invalida': 'Ungültige Option, bitte versuchen Sie es erneut.',
    'pedir_este_prato': "DIESES GERICHT BESTELLEN.",
    'pergunta_fazer_login': 'Möchten Sie sich anmelden (Ihre Präferenzen werden für zukünftige Vorschläge gespeichert) oder direkt zum Menü gehen?',
    'personalize': "Passen Sie Ihr Gericht an",
    'restricao_alimentar_cliente': 'Diätetische Einschränkung: ',
    'retirar_ingrediente': "Zutat entfernen",
    'rotina_desenvolvimento': 'Routine in Entwicklung...',
    'saida': "Programm wird beendet.",
    'sazonal': "Saisonal",
    'sem_Gluten': "Glutenfrei",
    'sem_Lactose': "Laktosefrei",
    'sem_ingredientes_adicionados': "Es werden keine Zutaten hinzugefügt.",
    'sem_ingredientes_retirados': "Es werden keine Zutaten entfernt.",
    'senhas_nao_conferem': "Passwörter stimmen nicht überein. Bitte versuchen Sie es erneut.",
    'telefone_cliente': 'Telefon: ',
    'vegetariano': 'Vegetarier',
    'video': "Präsentationsvideo des Gerichts",
    'video_nao_encontrado': "Videodatei nicht gefunden.",
    'voltar': "Zurück"
}
}

def get_mensagem_navegacao(idioma, chave):
    """Returns the message for the specified language and key."""
    return mensagens[idioma].get(chave, "Mensagem não encontrada")
